[workspace]

members = [
    "ch02/sec31",
    "ch02/sec32",
    "ch02/sec33",
    "ch02/sec34",
    "ch02/sec35",
    "ch02/sec36",
    "ch02/sec37",
    "ch02/sec38",
    "ch02/sec39",
    "ch03/sec81",
    "ch04/sec70",
    "ch07/sec11",
]
