[package]
name = "sec542"
version = "0.1.0"
edition = "2021"
authors = ["Keith Noguchi <hack@noguchi.us>"]

[dependencies]
tokio = { version = "1.22", features = ["rt-multi-thread", "sync", "macros", "time"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = "0.3"
