[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Keith Noguchi <hack@noguchi.us>"]

[dependencies]
async-std = "1"
serde_json = "1.0"
group = { path = "../group" }
state = { path = "../state" }
protocol = { path = "../protocol" }
connection = { path = "../connection" }
