[package]
name = "sec532"
version = "0.1.0"
edition = "2021"
authors = ["Keith Noguchi <hack@noguchi.us>"]

[dependencies]
futures = "0.3"
nix = { version = "0.25", default-features = false, features = ["event"] }
