[package]
name = "dclient"
version = "0.1.0"
edition = "2021"
authors = ["Keith Noguchi <hack@noguchi.us>"]

[dependencies]
async-std = "1"
libp2p = { version = "0.48", features = ["dns-async-std"] }
