[package]
name = "sec239"
version = "0.1.0"
edition = "2021"
authors = ["Keith Noguchi <keith@noguchi.us>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
