[package]
name = "sec512"
version = "0.1.0"
edition = "2021"

[dependencies.futures-lite]
version = "1.12.0"
default-features = false

[dependencies]
async-executor = "1.5.0"
async-io = "1.12.0"
async-lock = "2.6.0"
async-net = "1.7.0"

tracing = "0.1.37"
tracing-subscriber = "0.3.16"
